### PR TITLE
Exporting the logger

### PR DESCRIPTION
**Pull request by deanhaber**

### CODE REVIEW

**Comment by erezbi** [comment]
Are you using this?
How did you test it?

**Comment by offerakrabi** [comment]
This is the logger for the sdk - would it be right to use it in the skill? This way we can differentiate between logs from the sdk and the skill.
Maybe we should add a logger to the boilerplate or create a new logger in the sdk specifically for the skill?

**Comment by deanhaber** [comment]
@erezbi I've tested it in the code (and forgot to add that example in the SDK)
@offerakrabi I've noticed that they are currently using that logger a lot, so removing it will be a breaking change.
What we CAN do is just adding tags/different logs level for the SDK

**Comment by offerakrabi** [comment]
I think that is what we should do, add a tag for user logs - that way we know which logs come from the user and which come from the sdk.

**Comment by erezbi** [comment]
Accepting it. 
@offerakrabi and @deanhaber , I agree with both of you that we should add some levels or at least some way to distinct between log messages coming from the SDK and log messages coming from the skill developer using the SDK.
We should add this, but as @deanhaber mentioned, we don't want to cause breaking changes now. We can add this later.

**Pull request merged**
