### PR TITLE
added inConversation variable to evaluation response object

### PR DESCRIPTION
**Pull request by offerakrabi**
this variable tells if the skill is in the middle of a conversation.
also added the isInConversation function that sets the variable to true.
default value is false

### CODE REVIEW

**Comment by offerakrabi** [comment]
@erezbi 
It sets the inConversation to true, I can change it to setIsInConversation.
Also I can change it so it receives a parameter (true/false)

**Comment by erezbi** [comment]
I would go for setInConversation() and lose the 'is' in the name.

**Comment by erezbi** [comment]
shouldn't this go to the pre-release branch?
I think we should wait and get some feedback on current 'master' before we continue moving things around. in any case this will only be relevant once we release the improvements for the 'previous-skill' considerations in routing.

**Comment by offerakrabi** [comment]
You are right, I thought this was for the pre-release, I'll cancel it

**Pull request closed without merging**
