### PR TITLE
Stringify the Request logger.

### PR DESCRIPTION
**Pull request by nguyen-j**
Stringify the Request logger to show all key attributes. This will help with scanning through the request object on the console, or copy and pasting into a JSON formatter

### CODE REVIEW

**Comment by erezbi** [comment]
How was this tested?

**Comment by jnguyen1294** [comment]
It was tested on the Automotive skills -- checking that stringifying the JSON request object for a log statement did not throw any errors and that it printed out a more detailed JSON object.

**Comment by erezbi** [comment]
Great! Thanks!
Can you please open the pull request to pre-release branch instead of master?

**Comment by jnguyen1294** [comment]
It was tested on the Automotive skills -- checking that stringifying the JSON request object for a log statement did not throw any errors and that it printed out a more detailed JSON object.

(re-adding comment on correct github account)

**Comment by nguyen-j** [comment]
It was tested on the Automotive skills -- checking that stringifying the JSON request object for a log statement did not throw any errors and that it printed out a more detailed JSON object.

(re-adding comment on correct github account)

**Pull request merged**
